### ISSUE TITLE
Monitor view shows lost connection frequently

### ISSUE THREAD

**Issue by fsegatz** [loociano/MPSM2NetworkPrinting#12]
MP Select Mini V2
Plugin version: 0.5.0
Cura version: 4.6.1

As the title says: 
Approx. every 5-20 seconds Cura reports a lost connection to the printer in the monitor view. 
![MMSM2NetworkPrintingBug](https://user-images.githubusercontent.com/53816763/85952460-c5d50c80-b969-11ea-8659-09a2998fdeea.png)

 I can't tell if it is an actually lost or just a bug.
After 1-3 seconds the monitoring window for the MP returns.

**Comment by loociano** [comment]
Hi @fsegatz, thanks for reporting.

I am unable to reproduce on 0.5.0 with my printer; this might be a connectivity issue.

- Does this issue occur consistently if you restart the printer and Cura?
- Is the printer and the computer running Cura close to your router?
- Have you used the default Web UI before installing the plugin? If so, did you experience any issue?

Could you share your `cura.log`? On Cura, go to Help -> Show Configuration Folder.

**Comment by fsegatz** [comment]
Sorry for the long wait.
When the problem occured the log repeatedly shows following:

**020-06-28 18:00:36,987** - DEBUG - [MainThread] MPSM2NetworkPrinting.src.network.DeviceManager._on_printer_heartbeat 
[313]: Discovered device timed out. Stopping device.
**2020-06-28 18:00:36,987** - DEBUG - [MainThread] MPSM2NetworkPrinting.src.MPSM2NetworkedPrinterOutputDevice.close 
[310]: Closing.
**2020-06-28 18:00:39,143** - DEBUG - [MainThread] MPSM2NetworkPrinting.src.network.DeviceManager._on_printer_heartbeat 
[325]: Printer at 192.168.2.217 is up again. Reconnecting.
**2020-06-28 18:00:39,144** - DEBUG - [MainThread] MPSM2NetworkPrinting.src.network.DeviceManager.connect_to_active_machine 
[65]: Connecting to active machine.
**2020-06-28 18:00:39,144** - DEBUG - [MainThread] MPSM2NetworkPrinting.src.network.DeviceManager._connect_to_output_device 
[288]: Connecting to Output Device with key: manual:192.168.2.217.
**2020-06-28 18:00:39,145** - DEBUG - [MainThread] MPSM2NetworkPrinting.src.MPSM2NetworkedPrinterOutputDevice.connect 
[303]: Connecting.

**Does this issue occur consistently if you restart the printer and Cura?**
_Now that i am testing again it doesn't occur. I will keep an eye on it._
**Is the printer and the computer running Cura close to your router?**
_Computer and printer are approx. 7m away from the router with two walls in between. I haven't experienced any connectivity issues with any device so far. Downloadrate is at least 10Mbit/s _
**Have you used the default Web UI before installing the plugin? If so, did you experience any issue?**
_I have not used the Web UI before._

**Comment by loociano** [comment]
Thanks @fsegatz. This seems to be a temporary network issue. Please reopen if the issue reoccurs.
