### ISSUE TITLE
v0.5.0 causes CURA 4.8.0 to hang when clicking "Add Printer by IP"

### ISSUE THREAD

**Issue by junkjunker** [loociano/MPSM2NetworkPrinting#14]
I've got the problem that as soon as I click on "Add Printer by IP" Cura hangs.  It never recovers and I have to force close.

Windows 7 x64 Ultimate, Cura 4.8.0, MPSM V2.

Thanks!
![image](https://user-images.githubusercontent.com/25068787/111574099-704bc480-8771-11eb-978a-4a471680c7ec.png)

**Comment by loociano** [comment]
Hi @junkjunker,

Thanks for reporting this issue. I am unable to reproduce: I installed Cura 4.8 with plugin 0.5.0 and was able to add the printer.

- Did you upgrade from a previous Cura version or installed 4.8 fresh?
- Does it hang before or after installing the plugin?

The reason for hanging might be found in the Cura log file. Could you attach or email me your C:\Users\<user>\AppData\Roaming\cura\4.8\cura.log?

**Comment by loociano** [comment]
@junkjunker, please re-open if the issue persists.
