### ISSUE TITLE
Webcam view in Monitor tab

### ISSUE THREAD

**Issue by bmelim** [loociano/MPSM2NetworkPrinting#5]
Under Monitor in Cura, is it possible under the current view to have a webcam view of the printer? Perhaps being able to add an IP for the webcam?

**Comment by loociano** [comment]
Thanks @bmelim for suggesting this idea!

Since a webcam cannot be connected directly to the printer (at least without an adapter and/or a firmware change), are you considering the use case of a Wi-Fi IP webcam or a regular webcam attached to a computer?

**Comment by bmelim** [comment]
An option to add an IP address for a webcam would be good. 
As an example, the printer is in another room, I use octoprint with a webcam attached, I can preview it in Cura in Monitor screen. 
If the plugin can have a field for a webcam preview, I can monitor the print progress as well as keeping an eye on it.

**Comment by loociano** [comment]
I am not familiar with OctoPrint. Does the OctoPrint plugin for Cura support the webcam view, or is it only available through a web browser?
