### ISSUE TITLE
v0.2.0 - stops working after a few prints

### ISSUE THREAD

**Issue by bmelim** [loociano/MPSM2NetworkPrinting#7]
Using Cura 4.6.1 - after a few prints the plugin doesn't seem to start the print. It does send the model to the printer as this is noticed on the screen. However, print doesn't start. Restarted the printer, restarted Cura, this then allows a couple of prints, then stops working.

Also, another bug noticed, sometimes it doesn't preheat the hot end or the bed, you have to do this manually.  If you set the temperature within the plugin, it works.

**Comment by loociano** [comment]
> Using Cura 4.6.1 - after a few prints the plugin doesn't seem to start the print. It does send the model to the printer as this is noticed on the screen. However, print doesn't start. Restarted the printer, restarted Cura, this then allows a couple of prints, then stops working.

Thanks @bmelim for reporting this issue, I'll try to reproduce. How many models did you print before encountering this issue? Was there enough space on the SD card? Were you able to manually start the print with the dial or was the printer unresponsive?

> Also, another bug noticed, sometimes it doesn't preheat the hot end or the bed, you have to do this manually. If you set the temperature within the plugin, it works.

This is an issue I noticed using the Web UI as well and already reported on #6. I am unsure what causes this, the hotend target temperature is set after the bed temperature reaches its target (a few minutes after starting the print). 

Could you insert the SD card on a PC and open cache.gc with a text editor, to confirm the gcode commands were transferred correctly? The first lines should contain commands M104 (set extruder temperature) and M109 (wait for extruder temperature). For example:

```
;FLAVOR:Marlin
...
M140 S65
M105
M190 S65
M104 S215
M105
M109 S215
```

**Comment by loociano** [comment]
@bmelim is this issue still occurring in newer versions?

**Comment by loociano** [comment]
Please reopen if the issue persists.
